### PR TITLE
Submission for advance task

### PR DESCRIPTION
**Pull request by Beccamak**
@jafsia @ruqaiyasattar  @Fadanka @PetraAG This is my advanced task submission please kindly review it.

### CODE REVIEW

**Comment by Fadanka** [comment]
Hello, @Beccamak thanks so much for the amazing work, please, could you provide access to the report for the advanced task to complete the review process? many thanks.

**Comment by Beccamak** [comment]
@Fadanka I'm deeply sorry for the oversight sir. I made neccesary adustments.

**Comment by Fadanka** [comment]
Hello @Beccamak thank you for making the adjustments,
Amazing work on the logos and brand name proposition they are very genuine and well-researched. We also appreciate the literature research on already existing payment solutions. This is definitely a very great contribution to the project. Good Job!

**Comment by Rebecca65** [comment]
@Fadanka Thank you so much for your review sir. Are there other things I could work on to make more contributions sir.

**Comment by Beccamak** [comment]
@Fadanka Thank you so much for your review sir. Are there other things I could work on to make more contributions sir.

**Pull request merged**
